---
abstract: 'auto control forking manager process.'
author:
  - 'Atsushi Kobayashi <nekokak _at_ gmail _dot_ com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::SharedFork: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Qudo-Parallel-Manager
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Prallel::Prefork: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/Qudo-Parallel-Manager.git
version: 0.01
